# Generated by Django 5.0.4 on 2024-04-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
